name: "Setup"
description: "Setup and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up Node.js and Bun
      uses: actions/setup-bun@v2
      with:
        bun-version-file: package.json

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
